# Generated by Django 3.2.23 on 2024-01-18 12:56

import blango_auth.managers.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blango_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', blango_auth.managers.user.CustomUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
